In [1]:
import numpy as np
import random

# These are all toy examples to start with and visualize

In [2]:
def create_subgenome(genome_len, transposon_len, genome_label, seed):
    # create subgenome 
    sub_g = np.ones(genome_len)*genome_label
    # insert transposon
    random.seed(seed) # for testing (probably want a different seed for each subgenome)
    start_t = int(random.random()*genome_len-transposon_len)
    end_t = start_t + transposon_len
    sub_g[start_t] = 50
    sub_g[end_t] = 50
    return sub_g

## Simulation 1 

- same genome replicated 3 times

In [62]:
# decide on size of genome and transposon
length_genome = 100
length_transposon = 10
# create subgenome 1
subgenome_label = 1
sub_g1 = create_subgenome(length_genome,length_transposon,subgenome_label,0)
# replication event 1
sub_g11 = np.concatenate((sub_g1,sub_g1), axis=0)
# replication event 2
sim1_genome = np.concatenate((sub_g1,sub_g11),axis=0)
len(sim1_genome)

300

In [63]:
sim1_genome

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,  1.,  1.,  1

## Simulation 2

- same genome replicated 2 times, and hybridized with a new species

In [3]:
# decide on size of genome and transposon
length_genome = 50
length_transposon = 5
# create subgenome 1
subgenome_label = 1
sub_g1 = create_subgenome(length_genome,length_transposon,subgenome_label,0)
# replication event
sub_g11 = np.concatenate((sub_g1,sub_g1), axis=0)

# create subgenome 2
subgenome_label = 2
sub_g2 = create_subgenome(length_genome,length_transposon,subgenome_label,2)
# hybridization event
sim2_genome = np.concatenate((sub_g11,sub_g2),axis=0)
len(sim2_genome)

150

In [4]:
sim2_genome

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,
        1.,  1.,  1., 50.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,
        1., 50.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2., 50.,
        2.,  2.,  2.,  2., 50.,  2.,  2.])

## Simulation 3 
- 2 species hybridized (2n), third species hybridized (3n)

In [69]:
# decide on size of genome and transposon
length_genome = 100
length_transposon = 10
# create subgenome 1
subgenome_label = 1
sub_g1 = create_subgenome(length_genome,length_transposon,subgenome_label,0)

# create subgenome 2
subgenome_label = 2
sub_g2 = create_subgenome(length_genome,length_transposon,subgenome_label,2)
# hybridization event
sub_g12 = np.concatenate((sub_g1,sub_g2), axis=0)

# create subgenome 3
subgenome_label = 3
sub_g3 = create_subgenome(length_genome,length_transposon,subgenome_label,3)
# hybridization event
sim3_genome = np.concatenate((sub_g12,sub_g3),axis=0)
len(sim3_genome)

300

In [70]:
sim3_genome

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2

## Simulation 4 

- 2 species hybridized (2n), genome replicated (4n), lost one copy (3n)

In [74]:
# decide on size of genome and transposon
length_genome = 100
length_transposon = 10
# create subgenome 1
subgenome_label = 1
sub_g1 = create_subgenome(length_genome,length_transposon,subgenome_label,0)

# create subgenome 2
subgenome_label = 2
sub_g2 = create_subgenome(length_genome,length_transposon,subgenome_label,2)
# hybridization event
sub_g12 = np.concatenate((sub_g1,sub_g2), axis=0)

# replication event
sub_g1212 = np.concatenate((sub_g12,sub_g12),axis=0)

# loss of one copy
sim4_genome = sub_g1212[length_genome:]
len(sim4_genome)

300

In [75]:
sim4_genome

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2., 50.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2., 50.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., 50.,  1.,  1.,  1.,  1.,  1.,  1

## Old ideas

In [8]:
# Simulation with atgc will keep in case we ever need this
alphabet = ['A','T','G','C']
length_genome = 100000
np.random.seed(0)
genome_start = "".join(list(np.random.choice(alphabet,length_genome)))

def make_transposon(length):
    a = ['A','T','G','C']
    inverted_seq = 'ATCGATCG'
    rev = 'GCTAGCTA'
    t = "".join(list(np.random.choice(a,length-16)))
    return inverted_seq + t + rev

make_transposon(60)

random.seed(0)
random.random()*length_genome


84442.18515250481