In [1]:
import numpy as np
from numpy.random import default_rng
from decoder import *

In [2]:
TRANSP_LEN = 10000
N_GEN = 100

rng = default_rng(0)
genome_size = 1000000000

In [3]:
def modify_subgenome(subgenome, gen_size):
    new_transp = rng.integers(low=0, high=gen_size - TRANSP_LEN + 1, size=1)
    new_subgenome = subgenome
    for i, transp in enumerate(subgenome):
        if new_transp in range(transp, transp + TRANSP_LEN):
            new_subgenome = np.delete(new_subgenome, i)
        if transp > new_transp:
            new_subgenome[i] = transp + TRANSP_LEN
    gen_size += TRANSP_LEN
    new_subgenome = np.sort(np.concatenate([subgenome, new_transp]))
    return new_subgenome, gen_size

In [4]:
def time_lapse(n_gens, subgenome, genome_size):
    for _ in range(n_gens):
        subgenome, genome_size = modify_subgenome(subgenome, genome_size)
        
    return subgenome, genome_size

In [5]:
subgenome1 = rng.integers(low=0, high=genome_size - TRANSP_LEN + 1, size=5)
subgenome2 = subgenome1
subgenome3 = subgenome1

new_subgenome1 = time_lapse(10, subgenome1, genome_size)[0]
new_subgenome2 = time_lapse(10, subgenome2, genome_size)[0]
new_subgenome3 = time_lapse(10, subgenome3, genome_size)[0]

In [6]:
new_subgenome1, new_subgenome2, new_subgenome3

(array([ 16527470,  40983114,  75249389, 307836344, 503642081, 543668481,
        606670041, 632325057, 637005318, 649462244, 729560331, 813330239,
        850695720, 912823833, 970821375]),
 array([  2738609,  40993114,  75259389, 277359819, 307856344, 394168888,
        554353721, 559951846, 637015318, 670926670, 729713819, 815919871,
        850705720, 857475721, 935152424]),
 array([ 22102612,  40993114,  75259389,  80403665,  89307640, 175685620,
        299729873, 307886344, 422721036, 481105070, 541522879, 637055318,
        846646774, 850725720, 863256186]))

In [8]:
# use decoder to find origins of simulation
check_replication(np.array([new_subgenome1, new_subgenome2, new_subgenome3]), False)
find_order(np.array([new_subgenome1, new_subgenome2, new_subgenome3]), False,-5)

Subgenome 1 and 2 originate from a single genome
Subgenome 1 and 3 originate from a single genome
Subgenome 2 and 3 originate from a single genome
Subgenome 1 was present before subgenomes 2 and 3
