In [1]:
import numpy as np
from numpy.random import default_rng

In [2]:
TRANSP_LEN = 10000
N_GEN = 100

rng = default_rng(0)
genome_size = 1000000000

In [3]:
def modify_subgenome(subgenome, gen_size):
    new_transp = rng.integers(low=0, high=gen_size - TRANSP_LEN + 1, size=1)
    new_subgenome = subgenome
    for i, transp in enumerate(subgenome):
        if new_transp in range(transp, transp + TRANSP_LEN):
            new_subgenome = np.delete(new_subgenome, i)
        if transp > new_transp:
            new_subgenome[i] = transp + TRANSP_LEN
    gen_size += TRANSP_LEN
    new_subgenome = np.sort(np.concatenate([subgenome, new_transp]))
    return new_subgenome, gen_size

In [4]:
def time_lapse(n_gens, subgenome, genome_size):
    for _ in range(n_gens):
        subgenome, genome_size = modify_subgenome(subgenome, genome_size)
        
    return subgenome, genome_size

In [9]:
subgenome1 = rng.integers(low=0, high=genome_size - TRANSP_LEN + 1, size=5)
new_subgenome1, genome_size1 = time_lapse(10, subgenome1, genome_size)
subgenome2 = new_subgenome1
new_subgenome1, genome_size1 = time_lapse(10, new_subgenome1, genome_size1)
new_subgenome2, genome_size2 = time_lapse(10, subgenome2, genome_size1)
subgenome3 = new_subgenome2
new_subgenome1 = time_lapse(10, new_subgenome1, genome_size1)[0]
new_subgenome2 = time_lapse(10, new_subgenome2, genome_size2)[0]
new_subgenome3 = time_lapse(10, subgenome3, genome_size2)[0]

In [10]:
new_subgenome1, new_subgenome2, new_subgenome3

(array([ 66081835,  66691342, 124574634, 125471883, 141087718, 149388345,
        218672050, 226266013, 241737132, 268005768, 272730679, 288382656,
        344403751, 369507844, 412988922, 430414550, 452549224, 491939274,
        512913596, 562388065, 624820444, 626666824, 637091359, 650360562,
        710485412, 758163423, 761712946, 778680950, 818340958, 825724230,
        841567280, 873542638, 929374930, 959347003, 966339366]),
 array([ 41699297,  61059091,  66101835,  66711342,  82122332, 145534453,
        149408345, 226276013, 231560074, 268015768, 288541972, 344403751,
        406670745, 430404550, 454835193, 512893596, 552817294, 554302402,
        560701676, 586350289, 594144257, 624840444, 650360562, 758153423,
        764451029, 802268461, 810015107, 819466212, 841557280, 848611145,
        858742718, 873552638, 929384930, 944922440, 966349366]),
 array([  9958343,  43090239,  61069091,  66111835,  66721342, 113414697,
        149418345, 226286013, 268015768, 288541972, 3444