In [63]:
import numpy as np
from numpy.random import default_rng
from decoder import *

In [5]:
TRANSP_LEN = 10000
N_GEN = 100

rng = default_rng(0)
genome_size = 1000000000

In [6]:
def modify_subgenome(subgenome, gen_size):
    new_transp = rng.integers(low=0, high=gen_size - TRANSP_LEN + 1, size=1)
    new_subgenome = subgenome
    for i, transp in enumerate(subgenome):
        if new_transp in range(transp, transp + TRANSP_LEN):
            new_subgenome = np.delete(new_subgenome, i)
        if transp > new_transp:
            new_subgenome[i] = transp + TRANSP_LEN
    gen_size += TRANSP_LEN
    new_subgenome = np.sort(np.concatenate([subgenome, new_transp]))
    return new_subgenome, gen_size

In [7]:
def time_lapse(n_gens, subgenome, genome_size):
    for _ in range(n_gens):
        subgenome, genome_size = modify_subgenome(subgenome, genome_size)
        
    return subgenome, genome_size

In [8]:
subgenome1 = rng.integers(low=0, high=genome_size - TRANSP_LEN + 1, size=5)
subgenome2 = subgenome1
subgenome3 = subgenome1

new_subgenome1 = time_lapse(10, subgenome1, genome_size)[0]
new_subgenome2 = time_lapse(10, subgenome2, genome_size)[0]
new_subgenome3 = time_lapse(10, subgenome3, genome_size)[0]

In [9]:
new_subgenome1, new_subgenome2, new_subgenome3

(array([ 16527470,  40983114,  75249389, 307836344, 503642081, 543668481,
        606670041, 632325057, 637005318, 649462244, 729560331, 813330239,
        850695720, 912823833, 970821375]),
 array([  2738609,  40993114,  75259389, 277359819, 307856344, 394168888,
        554353721, 559951846, 637015318, 670926670, 729713819, 815919871,
        850705720, 857475721, 935152424]),
 array([ 22102612,  40993114,  75259389,  80403665,  89307640, 175685620,
        299729873, 307886344, 422721036, 481105070, 541522879, 637055318,
        846646774, 850725720, 863256186]))

In [160]:
def get_transposons_in_common(chrom1,chrom2,r):
    chrom2 = [round(t,r) for t in chrom2]
    transposons_in_common = []
    for transposon in chrom1: # look at each transposon
        t = round(transposon,r)
        if t in chrom2: # count transposons in common
            transposons_in_common.append(transposon)
    return len(transposons_in_common)

def find_most_ancestral(list_chroms,v,r):
    common_t1_2 = get_transposons_in_common(np.array(list_chroms[0]),np.array(list_chroms[1]),r)
    common_t1_3 = get_transposons_in_common(np.array(list_chroms[0]),np.array(list_chroms[2]),r)
    common_t2_3 = get_transposons_in_common(np.array(list_chroms[1]),np.array(list_chroms[2]),r)
    
    ave_1 = (common_t1_2+common_t1_3)/2
    ave_2 = (common_t1_2+common_t2_3)/2
    ave_3 = (common_t2_3+common_t1_3)/2
    
    max_c = max(ave_1,ave_2,ave_3)
    if max_c == ave_1:
        print('Subgenome 1 is the most ancestral')
        most_ancestral = list_chroms[0]
    elif max_c == ave_2:
        print('Subgenome 2 is the most ancestral')
        most_ancestral = list_chroms[1]
    else:
        print('Subgenome 3 is the most ancestral')
        most_ancestral = list_chroms[2]
#     return most_ancestral, max(common_t1_2,common_t1_3,common_t2_3)

In [161]:
# use decoder to find origins of simulation
check_replication(np.array([new_subgenome1, new_subgenome2, new_subgenome3]), False)
find_most_ancestral(np.array([new_subgenome1, new_subgenome2, new_subgenome3]), True,-5)

Subgenome 1 and 2 seem to originate from a single genome
Subgenome 2 is the most ancestral
